name = "jsonlogic"
version = "1.0.7"
description = "A Gleam implementation of JSONLogic"
licences = ["Apache-2.0"]
repository = { type = "github", user = "horvathandris", repo = "json-logic-gleam" }

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_json = ">= 3.0.2 and < 4.0.0"
lenient_parse = ">= 3.0.1 and < 4.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
simplifile = ">= 2.3.0 and < 3.0.0"
filepath = ">= 1.1.2 and < 2.0.0"
gleam_community_ansi = ">= 1.4.3 and < 2.0.0"
